### ISSUE TITLE
Latest Ubuntu release issue

### ISSUE THREAD

**Issue by snoopy82481** [Pr0meth3us/hms-docker#16]
Wanted to let you know that Ubuntu 19.10 eoan does not have a docker repo available at the moment.  But, the repo from the previous version does have one.  In the setup.sh the line that adds the repository to /etc/apt/sources.list needs to be adjusted to "deb [arch=amd64] https://download.docker.com/linux/ubuntu disco stable" for now.  I tested it, and it does work with the current version of Ubunutu 19.10.

**Comment by Pr0meth3us** [comment]
I only want to support LTS versions of Ubuntu server for the time being since 19.10 will stop receiving security and maintenance updates in July of 2020. 

Once a new LTS version of Ubuntu server is released, I will check for compatibility and update the repo if necessary while also trying to keep support for 18.04 LTS.
