### ISSUE TITLE
 haugene/transmission-openvpn seems to be stuck at (health: starting) and failing.

### ISSUE THREAD

**Issue by alisohail** [Pr0meth3us/hms-docker#7]
made a fresh ubuntu 18 box and installed hms-docker. all seems to be okay except transmission docker is stuck at health:starting and eventually failing after timeout.

nothing in error logs :/

**Comment by Pr0meth3us** [comment]
I noticed this as well recently. I'll look into it.

**Comment by alisohail** [comment]
I guess there is nothing wrong with your script. It seems like there is a bug with the latest build of haugene/transmission-openvpn. If you try older version it works just fine.

**Comment by Pr0meth3us** [comment]
I've had my transmission container up for 26hrs now and it says it's healthy. After restarting the transmission container, it took somewhere between 3-8mins to change the status to ```healthy``` from ```health: starting```. I was hoping to get it narrowed down to like 5mins, but I got sidetracked and forgot to check, so it changed somewhere between 3 and 8mins. The container may only check every 5mins, so that's why it might have a delayed health start time.
